services:
  ecommerce.api:
    build:
      context: .
      dockerfile: src/ECommerce.Api/Dockerfile
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=ECommerceDb;User=sa;Password=Your_password123;TrustServerCertificate=true;
    depends_on:
      - db
    networks:
      - ecommerce-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - ecommerce-network

volumes:
  sql_data:

networks:
  ecommerce-network:
    driver: bridge
